### ISSUE TITLE
run_kubernetes workflow step names should allow dash

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper-config-essentials#17]
The `run_kubernetes` workflow takes a list of steps and run them as containers in kubernetes batch jobs.  You can optionally give every step a name, and the name can be used to construct the container name.  We also use the name to build environment variable names somewhere in the workflow.  This makes using of dash `-` illegal.  We should fix this so we can properly use dash in the step names.  Also, we should document that underscore is not allowed in the step names because it is not allowed as kubernetes resource name.

**Comment by wyardley** [comment]
Can we throw a validation error as well as document?
